name: tecbet
description: App de apostas fictÃ­cio - TecBet
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  http: ^1.2.0
  shared_preferences: ^2.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/banner1.png
    - lib/assets/banner2.png
    - lib/assets/banner3.png
    - lib/assets/logo.png
    - lib/assets/palmeiras.png
    - lib/assets/celtics.png
    - lib/assets/lakers.jpg
    - lib/assets/flamengo.jpg
    
carousel_slider: ^5.1.1
   

